/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NNUE_nnue_probe_nnue_NNUEJNIBridge */

#ifndef _Included_NNUE_nnue_probe_nnue_NNUEJNIBridge
#define _Included_NNUE_nnue_probe_nnue_NNUEJNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NNUE_nnue_probe_nnue_NNUEJNIBridge
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NNUE_nnue_1probe_nnue_NNUEJNIBridge_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     NNUE_nnue_probe_nnue_NNUEJNIBridge
 * Method:    eval
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NNUE_nnue_1probe_nnue_NNUEJNIBridge_eval__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     NNUE_nnue_probe_nnue_NNUEJNIBridge
 * Method:    eval
 * Signature: (I[I[I)I
 */
JNIEXPORT jint JNICALL Java_NNUE_nnue_1probe_nnue_NNUEJNIBridge_eval__I_3I_3I
  (JNIEnv *, jclass, jint, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
